// Generated by CoffeeScript 2.7.0
(function() {
  var square;

  square = function(x) {
    return x * x;
  };

  console.log(square(5));

  // Ensure that the DOM is ready
  $(function() {
    var linkElement;
    // Select the element with the ID 'link'
    linkElement = $('#link');
    // Log the selected element to the console
    return console.log(linkElement);
  });

}).call(this);
